### ISSUE TITLE
[TASK] Fix Asset transfer test for relayer

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/relayer#373]
## Overview

The asset transfer test fails to decrypt first encrypted commitment here

```ts
encryptedCommitments  [
  '0x73fd976ef559e7fa3233b79f3e592846036163ed44cd9ed7eeaf0f53529811e63d9f64c8099fafe8b079381eefeee487ca9850d8da167a08cccd981dc179c39a61d918e55502b0edb520c9e97aadfd627b74a2aa54c1419c0b60afe531147ac21b2dafc5aef5f31cd0f15ab4db16688682755bbde19300ee61444d702b51ee160205d94510d9052261d115832a8955e77762766e9e4334f6e0f9e34dce21e58e7f01bdc68f871c30',
  '0xc57c7f5112c6a6f56b3473612595ab3d7bb84363d8e0d314cb42a736181f8571c96c17ef03ab42e362cf9cdc8eae695294b4bfbf65aedd083b790ca04ebb3cb1570159d1cc2a536bd5aacb9eb35fafde738ec60751e3bd23cbafe559da0eb8e775f791aac02976931a0f340952ff472322df14c0b5f4f4caba2f6542a7511abb51c5c6b09b8c558102135c8568479838d293263a4269f1fa4746cfc6648e1f239269a299813f3c99'
]


const utxos = await Promise.all(
      encryptedCommitments.map(async (enc, index) => {
        try {
          const decryptedUtxo = await CircomUtxo.decrypt(bobKeypair, enc);
          // In order to properly calculate the nullifier, an index is required.
          decryptedUtxo.setIndex(index);
          decryptedUtxo.setOriginChainId(localChain1.chainId.toString());

```

### Error
```ts
Decryption failed:  Error: Decryption failed.
    at decrypt (/Users/salman01zz/Webb-Tools/relayer/tests/node_modules/@webb-tools/sdk-core/node_modules/eth-sig-util/src/index.ts:530:15)
    at Keypair.decrypt (file:///Users/salman01zz/Webb-Tools/relayer/tests/node_modules/@webb-tools/sdk-core/keypair.js:138:24)
    at Function.decrypt (file:///Users/salman01zz/Webb-Tools/relayer/tests/node_modules/@webb-tools/sdk-core/solidity-utils/circom-utxo.js:117:25)
    at file:///Users/salman01zz/Webb-Tools/relayer/tests/test/evm/RelayerTxTransfer.test.ts:227:50
    at Array.map (<anonymous>)
    at Context.<anonymous> (file:///Users/salman01zz/Webb-Tools/relayer/tests/test/evm/RelayerTxTransfer.test.ts:225:28)
    at runMicrotasks (<anonymous>)
```

**Comment by salman01zp** [comment]
Fixed by #445
